export default Object.freeze([
        { name: "catering", text: "餐饮" },
        { name: "traffic", text: "交通" },
        { name: "shopping", text: "购物" },
        { name: "dailysupplies", text: "日常" },
        { name: "foods", text: "食材" },
        { name: "clothing", text: "衣服" },
        { name: "games", text: "娱乐" },
        { name: "study", text: "学习" },
        { name: "fruits", text: "水果" },
        { name: "trip", text: "出行" },
        { name: "medical", text: "医疗" },
        { name: "communitcation", text: "通讯" },
        { name: "beverages", text: "饮品" },
        { name: "hairdressing", text: "化妆" },
        { name: "automobile", text: "汽车" },
        { name: "authors", text: "其他" },
]);
